# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://myeong-jun.github.io
title: myeong-jun study blog
email: maypaul1@naver.com
author: MyeongJun Kwon
description: > # "Write an awesome description for your new site here. 
  This blog is my study memo.
copyright: 'Made in 2020 by myeong-jun'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: instagram
    url: https://www.instagram.com/maypaul1/?hl=ko
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100003462615271
  - title: github
    url: https://github.com/myeong-jun
  

theme: jekyll-theme-cayman
